<a href="https://colab.research.google.com/github/zlfaris/Data-Mining-1/blob/main/Data_Preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

# Baca file Excel
df_original = pd.read_excel('Data-Penjualan.xlsx')

# Ambil 1000 baris pertama
df_1015 = df_original.head(1000)

print("Menampilkan 1000 data pertama:")
display(df_1015)

# Simpan DataFrame ke file CSV
df_1015.to_csv('Data-Penjualan (Collection Data).csv', index=False)

# Info data
df_1015.info()

Menampilkan 1000 data pertama:

,No.Faktur,Tgl Order,Sales,Pelanggan,Jumlah Bruto (Rp),Total Discount (Rp),Jumlah Netto (Rp),Retur (Rp),Total (Rp),DiscD,DiscC,Tgl DO,No DO,Drive,Penagih,Status,Flag,Tgl FP,No FP
0,VRD25GAJGB,2025-08-01,Sahrul ( Prapani ),ALFA MIDI,67273668,3652960,63620708,0,63620708,0.0,0,2025-08-04,DO25GATP,Borongan 2,NaN,NaN,FP,2025-08-04,005.25.71495877
1,VRD25GAJMP,2025-08-01,Sales B2B Campina,INDOMARET FRVE - SUNGAI POSO,942400,235600,706800,324000,382800,0.0,0,2025-07-10,DO25GAVX,Suwakir ( Prapani ),NaN,NaN,FP,2025-08-06,005.25.71496899
2,VRD25GAOOM,2025-08-01,Sahrul ( Prapani ),MATAHARI HYPERMART - MAMUJU,1086389,0,1086389,0,1086389,0.0,0,2025-07-25,DO25GBPE,Toko,NaN,Lunas,FP,2025-08-04,005.25.71496089
3,VRD25GAOYJ,2025-08-01,Sales B2B Campina,ALFA MIDI NE45 - POROS KARIANGO TENRIGANGKAE,2040000,510000,1530000,1530000,0,0.0,0,2025-07-19,DO25GBQQ,Steven Aulia Prapani,NaN,Lunas,FP,NaT,NaN
4,VRD25GASLQ,2025-08-01,Sahrul ( Prapani ),CARREFOUR TRANS STUDIO,1858801,37176,1821625,0,1821625,0.0,0,2025-07-18,DO25GBMS,Ardiansyah Driver ( Prapani ),NaN,NaN,FP,2025-07-21,004.25.97534652
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,VRD25HAANK,2025-08-02,Sales B2B Campina,INDOMARET T0M7 - POROS HARTACO,382000,95500,286500,99000,187500,0.0,0,2025-08-04,DO25HAFW,Adi Driver ( Prapani ),NaN,NaN,FP,2025-08-04,005.25.71495884
996,VRD25HAANL,2025-08-02,Sales B2B Campina,INDOMARET T2F4 - DIPONEGORO,330200,82550,247650,0,247650,0.0,0,2025-08-04,DO25HAFV,Suwakir ( Prapani ),NaN,NaN,FP,2025-08-04,005.25.71495899
997,VRD25HAANM,2025-08-02,Sales B2B Campina,INDOMARET T36R - MACCINI RAYA,767500,191875,575625,0,575625,0.0,0,2025-08-04,DO25HAFV,Suwakir ( Prapani ),NaN,NaN,FP,2025-08-04,005.25.71495900
998,VRD25HAANN,2025-08-02,Sales B2B Campina,INDOMARET TBLR - DG. TATA RAYA,749600,187400,562200,0,562200,0.0,0,2025-08-04,DO25HAFW,Adi Driver ( Prapani ),NaN,NaN,FP,2025-08-04,005.25.71495885
999,VRD25HAANO,2025-08-02,Sales B2B Campina,INDOMARET TGQD - KERUNG KERUNG,328000,82000,246000,246000,0,0.0,0,2025-08-04,DO25HAFV,Suwakir ( Prapani ),NaN,Lunas,FP,NaT,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   No.Faktur            1000 non-null   object
 1   Tgl Order            1000 non-null   datetime64[ns]
 2   Sales                1000 non-null   object
 3   Pelanggan            1000 non-null   object
 4   Jumlah Bruto (Rp)    1000 non-null   int64
 5   Total Discount (Rp)  1000 non-null   int64
 6   Jumlah Netto (Rp)    1000 non-null   int64
 7   Retur (Rp)           1000 non-null   int64
 8   Total (Rp)           1000 non-null   int64
 9   DiscD                1000 non-null   float64
 10  DiscC                1000 non-null   int64
 11  Tgl DO               1000 non-null   datetime64[ns]
 12  No DO                1000 non-null   object
 13  Drive                1000 non-null   object
 14  Penagih              89 non-null     object
 15  Status               660 non-null    object
 16  Flag                 480 non-null    object
 17  Tgl FP               962 non-null    datetime64[ns]
 18  No FP                962 non-null    object
dtypes: datetime64[ns](3), float64(1), int64(6), object(9)
memory usage: 148.6+ KB

In [ ]:

# Data Integration
import pandas as pd

# Baca file CSV
df_original = pd.read_csv("Data-Penjualan (Collection Data).csv")

# Cek dulu nama kolom yang tersedia
print("Daftar kolom di dataset:")
print(df_original.columns.tolist())

# Salin dataframe
df_integrasi = df_original.copy()

# Ubah kolom tanggal ke format datetime (hanya jika ada di dataset)
date_columns = ['Tgl Order', 'Tgl DO', 'Tgl FP']
for col in date_columns:
    if col in df_integrasi.columns:
        df_integrasi[col] = pd.to_datetime(df_integrasi[col], errors='coerce')

# Bersihkan dan ubah kolom uang ke format angka
currency_columns = ['Jumlah Bruto (Rp)', 'Total Discount (Rp)', 'Jumlah Netto (Rp)', 'Retur (Rp)', 'Total (Rp)']
for col in currency_columns:
    if col in df_integrasi.columns:
        df_integrasi[col] = (
            df_integrasi[col]
            .astype(str)
            .str.replace(r'[^\d.-]', '', regex=True)
        )
        df_integrasi[col] = pd.to_numeric(df_integrasi[col], errors='coerce')

# Isi data kosong (NaN)
for col in currency_columns:
    if col in df_integrasi.columns:
        df_integrasi[col] = df_integrasi[col].fillna(0)

text_cols = ['Sales', 'Pelanggan', 'Drive', 'Penagih', 'Status']
for col in text_cols:
    if col in df_integrasi.columns:
        df_integrasi[col] = df_integrasi[col].fillna('Unknown')

# Simpan ke CSV
df_integrasi.to_csv("data_integrasi.csv", index=False)
print("File 'data_integrasi.csv' berhasil disimpan.")

Daftar kolom di dataset:
['No.Faktur ', 'Tgl Order ', 'Sales', 'Pelanggan', 'Jumlah Bruto (Rp)', 'Total Discount (Rp)', 'Jumlah Netto (Rp)', 'Retur (Rp) ', 'Total (Rp) ', 'DiscD', 'DiscC ', 'Tgl DO', 'No DO', 'Drive', 'Penagih', 'Status', 'Flag', 'Tgl FP', 'No FP']
File 'data_integrasi.csv' berhasil disimpan.

In [ ]:
import pandas as pd

hasil_analisis = {}

# Top 10 Pelanggan
try:
    top_pelanggan = df_integrasi.groupby('Pelanggan')['Jumlah Netto (Rp)'].sum().nlargest(10)
    hasil_analisis["Top 10 Pelanggan Berdasarkan Netto (Rp)"] = top_pelanggan
except KeyError:
    print("⚠️ Kolom 'Pelanggan' atau 'Jumlah Netto (Rp)' tidak ada.")

# Top 10 Sales
try:
    top_sales = df_integrasi.groupby('Sales')['Jumlah Netto (Rp)'].sum().nlargest(10)
    hasil_analisis["Top 10 Sales Berdasarkan Penjualan Netto (Rp)"] = top_sales
except KeyError:
    print("Kolom 'Sales' atau 'Jumlah Netto (Rp)' tidak ada.")

# Simpan ke file TXT
with open("data_analisis.txt", "w", encoding="utf-8") as f:
    for judul, data in hasil_analisis.items():
        f.write(f"{judul}\n")
        f.write(data.to_string())
        f.write("\n\n")

print("Hasil analisis berhasil disimpan ke 'data_analisis.txt'")

Hasil analisis berhasil disimpan ke 'data_analisis.txt'

In [ ]:
# Tahap 2 (Bagian 3): Validasi Data

# Salin dataframe
df_validasi = df_integrasi.copy()

# Validasi Duplikat
jumlah_duplikat = df_validasi.duplicated().sum()
df_validasi.drop_duplicates(inplace=True)
jumlah_setelah_dihapus = len(df_validasi)

# Validasi Data Kosong
jumlah_kosong = df_validasi.isnull().sum().sum()

# Simpan ringkasan ke TXT
with open("data_validasi.txt", "w", encoding="utf-8") as f:
    f.write("Validasi Data\n")
    f.write(f"Jumlah baris duplikat: {jumlah_duplikat}\n")
    f.write(f"Jumlah baris setelah hapus duplikat: {jumlah_setelah_dihapus}\n")
    f.write(f"Jumlah baris yang datanya tidak terisi: {jumlah_kosong}\n")

# Simpan data validasi ke CSV juga
df_validasi.to_csv('data_validasi.csv', index=False)

print("File 'data_validasi.csv' dan 'data_validasi.txt' berhasil disimpan.")

File 'data_validasi.csv' dan 'data_validasi.txt' berhasil disimpan.