<a href="https://colab.research.google.com/github/zlfaris/Data-Mining-1/blob/main/integrasidata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

# Akses langsung dari Google Sheets (ubah export ke CSV)
sheet_url = "https://docs.google.com/spreadsheets/d/1YezL7SJCypFn9uWbeDSuhSUhaTBQU_z2/export?format=csv"
data = pd.read_csv(sheet_url)

# Simpan hasil integrasi
data.to_csv("data_integration.csv", index=False)
data.head()

,Laporan Penjualan,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,Tgl_Order,8/1/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,No.Faktur,Tgl Order,Sales,Pelanggan,Jumlah Bruto (Rp),Total Discount (Rp),Jumlah Netto (Rp),Retur (Rp),Total (Rp),DiscD,DiscC,Tgl DO,No DO,Drive,Penagih,Status,Flag,Tgl FP,No FP
2,VRD25GAJGB,8/1/2025,Sahrul ( Prapani ),ALFA MIDI,67.273.668,3.652.960,63.620.708,0,63.620.708,0,0,8/4/2025,DO25GATP,Borongan 2,NaN,NaN,FP,8/4/2025,005.25.71495877
3,VRD25GAJMP,8/1/2025,Sales B2B Campina,INDOMARET FRVE - SUNGAI POSO,942.400,235.600,706.800,324.000,382.800,0,0,7/10/2025,DO25GAVX,Suwakir ( Prapani ),NaN,NaN,FP,8/6/2025,005.25.71496899
4,VRD25GAOOM,8/1/2025,Sahrul ( Prapani ),MATAHARI HYPERMART - MAMUJU,1.086.389,0,1.086.389,0,1.086.389,0,0,7/25/2025,DO25GBPE,Toko,NaN,Lunas,FP,8/4/2025,005.25.71496089